name: CI for Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Install and Cache Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'

      # Restore node_modules cache before installing dependencies
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install pnpm
      - name: Install pnpm 9.0.4
        run: npm install -g pnpm@9.0.4

      # Install dependencies (pnpm)
      - name: Install dependencies
        run: pnpm install

      # Save node_modules cache after installing dependencies
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup  # Run after the setup job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'

      # Restore node_modules cache before running tests
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm 9.0.4
        run: npm install -g pnpm@9.0.4

      # Install dependencies (pnpm)
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test:ci

      - name: Run tests coverage
        run: pnpm run test:coverage
